### ISSUE TITLE
Get generic key for meetup.com API

### ISSUE THREAD

**Issue by xMartin** [OpenTechSchool/www.opentechschool.org#1]
For using the meetup.com API you need a key. It is a personal key. We should find a way to have a key that is not related to a real person. Maybe create a user just for that.

**Comment by xMartin** [comment]
At the moment my personal key is used which is discouraged to publish.

https://github.com/OpenTechSchool/www2.opentechschool.org/commit/756b33727f76e74b7f54b410ccc38069f147c785#L1L-1

**Comment by gnunicorn** [comment]
@stefanhoth : could you pls ask your meetup.com contact on what is the preferred way of doing this for public data? Maybe we can get a specific key not attached to any user with real rights or smth?

**Comment by stefanhoth** [comment]
Just create a new user like "OpenTechSchool Admin" and give it the necessary rights and use it's key for stuff.
