### ISSUE TITLE
YouTube and website contact links missing

### ISSUE THREAD

**Issue by qubodup** [OpenTechSchool/www.opentechschool.org#132]
http://www.youtube.com/user/OpenTechSchool is missing from the "connect with us" footer column.

Information whom to contact about the website - for example about broken links - is missing from http://www.opentechschool.org/contact.html Perhaps a link to this issue tracker would make sense on that page.

**Comment by xMartin** [comment]
Closing in favor for two new separate issues for the two topics. #239 #240
