### ISSUE TITLE
Make the site work on other domains for better forking

### ISSUE THREAD

**Issue by friedger** [OpenTechSchool/www.opentechschool.org#133]
All links should be changed to include the jekyll config {{site.baseurl}} before them, allowing one to switch.

**Comment by Ivoz** [comment]
Why do you need it up on other domains though?

**Comment by Ivoz** [comment]
I've pushed a branch on my fork which does this, I'm still unsure on exactly why its needed...

https://github.com/Ivoz/www.opentechschool.org/tree/link-rebase

**Comment by Ivoz** [comment]
Still needs city image links to be relative in the css, I think, but should be mostly done
