### ISSUE TITLE
Fix team images up

### ISSUE THREAD

**Issue by Ivoz** [OpenTechSchool/www.opentechschool.org#140]
- [ ] Hugo Herter needs an image!
- [ ] Not sure what Nino Bosteels' image is about?
- [ ] At the moment philipp's image is 221x222 pixels, which leaves a hole in http://www.opentechschool.org/team.html
  
  It needs to be 222x222 or 221x221 or 200x200
  
   http://www.opentechschool.org/images/team/philipp.jpg
- [ ] Karla's image should be scaled down
  
  http://www.opentechschool.org/images/team/karla.jpg

**Comment by Ivoz** [comment]
@friedger could you look at first two?

**Comment by lehmannro** [comment]
Bump.  I'm going to replace images with a large question mark or some such soon if there's no better picture found.

**Comment by friedger** [comment]
@lehmannro Go ahead! Maybe @zharkov can help

**Comment by romamile** [comment]
Works for me, I don't think those concerned will be very ... concerned!

**Comment by Ivoz** [comment]
Closing this as too old
