### ISSUE TITLE
Site broken on mobile

### ISSUE THREAD

**Issue by Ivoz** [OpenTechSchool/www.opentechschool.org#162]
We should try being responsive again...

Looking from Chrome on Nexus 5:

![OTS on nexus 5](http://i.imgur.com/rk2oKmh.jpg)

**Comment by xMartin** [comment]
Confirmed. The page is a total mess for width < 768px.

**Comment by phumberdroz** [comment]
![Screenshot Mobile View](https://i.imgur.com/h2tzFp4.png)

Looks fine for me.
