### ISSUE TITLE
Hackership text on OTS homepage outdated

### ISSUE THREAD

**Issue by Charlottehayne** [OpenTechSchool/www.opentechschool.org#169]
@ligthyear   :) 
![image](https://cloud.githubusercontent.com/assets/4541220/4726143/98c37e86-595f-11e4-9503-ff8d61f59063.png)

**Comment by gsambrotta** [comment]
@Charlottehayne if you have the new text, I can update it

**Comment by gsambrotta** [comment]
Close after redesign the page
