### ISSUE TITLE
Re-design "last news" and "upcoming events"

### ISSUE THREAD

**Issue by gsambrotta** [OpenTechSchool/www.opentechschool.org#182]
Let's redesign our "last news" and "upcoming events" on home page
The idea is to do something like that:
![schermata 2015-04-20 alle 22 03 24](https://cloud.githubusercontent.com/assets/1055531/7239323/5b0bf964-e7a9-11e4-9f63-53da11fb1998.png)

**Comment by gsambrotta** [comment]
Would be cool also if we can have 4 upcoming events and 5 news, so they have almost the same high

**Comment by lehmannro** [comment]
Yes, please!  I never liked the oddly-coloured bars we had in there.

I think the number of events might just be a setting in the Javascript, but maybe it's also some oddity of the Meetup/Feed API.  If you don't beat me to it I can take a closer look.

**Comment by gsambrotta** [comment]
on PR #185
