### ISSUE TITLE
Add OTS BLN Facebook link

### ISSUE THREAD

**Issue by xMartin** [OpenTechSchool/www.opentechschool.org#191]

**Comment by stefanhoth** [comment]
What's the link and where should it go?

**Comment by xMartin** [comment]
1. https://www.facebook.com/opentechschool.berlin
2. don't know

**Comment by Ivoz** [comment]
Probably just in https://github.com/OpenTechSchool/www.opentechschool.org/blob/gh-pages/_cities/berlin.md

There is no special metadata part for a facebook group / link at present

**Comment by xMartin** [comment]
Done with https://github.com/OpenTechSchool/www.opentechschool.org/pull/211
