### ISSUE TITLE
Markdown lists broken

### ISSUE THREAD

**Issue by abelards** [OpenTechSchool/www.opentechschool.org#198]
Hi,
when reading many pages [1] I can see the bullet points (or the bold text) are broken.
Did you (or github) update Jekyll or change the markdown interpreter?
In my own blog adding a blank line before the lists does the trick (but adds whitespace you might not want), but then again it may only be an issue of markdown renderer.
I can change whichever pages you want [2] adding these blank lines, if you're OK with this?
Cheers,

[1] e.g. http://www.opentechschool.org/handbooks/city-blueprint.html
[2] like https://github.com/OpenTechSchool/www.opentechschool.org/blob/gh-pages/handbooks/city-blueprint.md

**Comment by gnunicorn** [comment]
Hello @abelards, 

Yes, it appears there has been a change in the stack that has unnoticed consequences. Thank you for reporting. We'd gladly take you up on the offer: if you want to prepare and send a PR fixing those by adding blank lines (maybe add a screenshot as proof ;) ), that'd be amazing!

Ben

**Comment by abelards** [comment]
I'm not sure about proof, I guess the hidden question was:
how do you generate your jekyll and with which versions/config?

I've seen `kramdown` in the config and their doc confirms what I've seen[1].
I will definitely send some PRs in my own time, say a page a day or so :)

[1] http://kramdown.gettalong.org/quickref.html#lists

```
This is a paragraph.
1. This is NOT a list.

1. This is a list!
```

**Comment by gnunicorn** [comment]
Thanks for taking this on!

We only use gh-pages – so, whatever version they have running ;).

In doubt, IMHO it is enough proof to copy-paste the fixed files into a gists and let github render it there properly and take a screenshot of that :) .

**Comment by lehmannro** [comment]
Let's not put up arbitrary red tape around a "proof" here;  I'll gladly merge your PR.

We also have some workshops in Markdown, maybe these should be reviewed as well.

It seems there are no adverse effects to [having a blank line before bullet lists](http://johnmacfarlane.net/babelmark2/?text=Foo%0A*+Bar%0A%0AQuux%0A%0A*+Lorem).  FWIW, the [CommonMark spec](http://spec.commonmark.org/0.22/#example-250) disagrees with Kramdown on this matter.

**Comment by abelards** [comment]
Not sure if `dashboard.html` works (tried it, nothing shown).

Also this is pretty weird as SOME of the the Organisers' Schedule bullet points work with no blank line added (just after titles not just after text):
http://www.opentechschool.org/handbooks/workshops/organisers-schedule.html

**Comment by lehmannro** [comment]
`dashboard.html` requires a query parameter, such as:

http://www.opentechschool.org/dashboard?opentechschool-zurich

(It is, though, slightly broken in the sense that it does not do paging.  This leads to Berlin's last workshops falling under the table through all the Colearning.)

**Comment by Ivoz** [comment]
@abelards let me know if above commit solves all problems for this issue? Or is there anything else left to do.

http://www.opentechschool.org/handbooks/city-blueprint.html

**Comment by abelards** [comment]
Yup, that's fixed! Cheers,
