### ISSUE TITLE
Homepage intro div banner is weirdly left alined

### ISSUE THREAD

**Issue by Ivoz** [OpenTechSchool/www.opentechschool.org#208]
I'd think it should be nicely centered?

![homepage banner](https://i.imgur.com/fVnWzrh.jpg)

(note, if above image looks better than the actual homepage, it's likely because the image in your browser is on the left as well and isn't the full browser width :D )

**Comment by xMartin** [comment]
Fixed with https://github.com/OpenTechSchool/www.opentechschool.org/pull/207
