### ISSUE TITLE
Do we really need compass?

### ISSUE THREAD

**Issue by xMartin** [OpenTechSchool/www.opentechschool.org#217]
What exactly do we need [Compass](http://compass-style.org) for in addition to [SASS](http://sass-lang.com)?

If I get this right, Jekyll (and thus Github pages) has built-in support for SASS but not for Compass. In out current setup Compass needs to be executed separate from Jekyll and both the sources and the output needs to be committed. I think it could be much simpler and less error-prone without Compass.

**Comment by gnunicorn** [comment]
compass is from a time when neither jekyll nor github supported SASS yet. With todays setup we do not need it anymore, no.

I am totally in favor of moving that over, also to smaller and cleaner framework like bourbon.io .
