### ISSUE TITLE
Discussion widget shows pinned topics

### ISSUE THREAD

**Issue by lehmannro** [OpenTechSchool/www.opentechschool.org#219]
The discussion widget (at the very bottom of the landing page) shows the _WELCOME to OpenTechSchool FORUM_ post, which is rather unhelpful.

It should be a matter of filtering out on `topic.pinned_globally` if there's no option for `latest.json` to exclude them in the first place.

**Comment by xMartin** [comment]
Fixed by https://github.com/OpenTechSchool/www.opentechschool.org/pull/221 thanks!
