### ISSUE TITLE
Press Page

### ISSUE THREAD

**Issue by gnunicorn** [OpenTechSchool/www.opentechschool.org#23]
- Compile Materials
- Compile List of Coverage (Blogs)

**Comment by beatricemartini** [comment]
Downloadable materials:
- text: at least for now, how about using the "About" text?
- graphics: @Kriesse ?

List of coverage:
just added.

**Comment by gnunicorn** [comment]
Okay. About is added for all languages, but now we really have some ugly-switch-list there. @Kriesse , shall I make a separate issue about that or are you having that in mind still?

**Comment by Kriesse** [comment]
Just re-assign this to me, or make a separate issue. I won't have a lot of time before later tonight though, just FYI :)
