### ISSUE TITLE
Rename "Latest Topics" to "All Topics" on homepage

### ISSUE THREAD

**Issue by xMartin** [OpenTechSchool/www.opentechschool.org#237]
The "Discussion" widget has a link to "Latest Topics" on Discourse. But actually the widget is just there to display the latest topics. It should be labeled "All Topics" because that's what you want and get when you follow the link to Discourse.

**Comment by tzhongdev** [comment]
Hey i want to help. I am a noobie and try to fix this. Please reply me if its ok. 
Cheers

**Comment by xMartin** [comment]
Yes please! :) Join our chat if you have questions: https://gitter.im/OpenTechSchool/www.opentechschool.org
