### ISSUE TITLE
Chapters without stylesheet

### ISSUE THREAD

**Issue by phumberdroz** [OpenTechSchool/www.opentechschool.org#247]
Hey People,

Our Chapters do not seem to get the css anymore. (404)

@xMartin maybe it has to do with your recent changes ?

Best,

**Comment by xMartin** [comment]
Thanks @phumberdroz and nice to know you're around :)

I'm looking into it, strange... So looking forward to get rid of this old setup.

**Comment by xMartin** [comment]
Updated dependencies but that didn't help. No idea :(

Might be connected to this themes stuff we're using that is not really supported any more. Or not.

Anyone else?

**Comment by phumberdroz** [comment]
As a temporary work around we could remove the variable from https://github.com/OpenTechSchool/www.opentechschool.org/blob/gh-pages/_includes/_head.html#L44 (site.baseurl) and just put the slash in it since i do not think we will serve our website from a different location..

**Comment by Ivoz** [comment]
It seems we have fallen afoul doing things "the wrong way" along with quite a few other people, judging from the number of +1's. Eventually (github) jekyll updates have turned such usage from 'wrong' into broken.

https://github.com/github/pages-gem/issues/350

I (as far as I remember) had long ago assumed if we were on a domain's subpath, baseurl should be e.g `/subpath/` and if on the bare domain then `/`. 

On github's jekyll impl. in recent updates they've decided setting baseurl to `/` is bad, and if it's set as that, it will be reset to empty. So all path logic breaks and stuff on subpaths like chapter pages breaks. 

So there needs to be a commit to add a `/` after every usage of `site.baseurl`.

**Comment by phumberdroz** [comment]
That should work I will prepare a pull request later todaY

**Comment by phumberdroz** [comment]
8ffa26fc62e51e2f20f0b8a81039fa7af3c98354 fixxed

**Comment by xMartin** [comment]
:tada:
