### ISSUE TITLE
Bad sqliteman link. (opentechschool.github.io)

### ISSUE THREAD

**Issue by MvGulik** [OpenTechSchool/www.opentechschool.org#248]
Not sure if `opentechschool.github.io` link issues fall under `www.opentechschool.org` jurisdiction/responsibility. (*probably not, as I draw a blank on searching for SqliteMan here*)
But, I just need to dump this somewhere seemingly related so I can ignore it from now on end.

Here it is:
\- Page: http://opentechschool.github.io/sql-tutorial/installationguide.html
\- Links: those that link to "SqliteMan"
\- Issue: used URL should probably be "sqliteman.yarpen.cz/" and not "www.sqliteman.yarpen.cz/". As the latter one (*currently, don't know how it was in the past*) end in a 404 dead end.

... Run's off again, minus one burden.

**Comment by phumberdroz** [comment]
Fixxed here : https://github.com/OpenTechSchool/sql-tutorial/commit/701f1c5a2be9375371b0c6468de1f0d4dc2535d2
