### ISSUE TITLE
Stylesheets 404 on projects page

### ISSUE THREAD

**Issue by arky** [OpenTechSchool/www.opentechschool.org#249]
Receiving quite a few 404 errors on Projects page ( http://www.opentechschool.org/projects/ )

screen.css Failed to load resource: the server responded with a status of 404 (Not Found)
by-sa-cp.png Failed to load resource: the server responded with a status of 404 (Not Found)
screen.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by phumberdroz** [comment]
8ffa26fc62e51e2f20f0b8a81039fa7af3c98354 fixed
