### ISSUE TITLE
Adding machine learning

### ISSUE THREAD

**Issue by iteachmachines** [OpenTechSchool/www.opentechschool.org#260]
Hello first of all thanks for starting this beautiful initiative.
I wanted to know about how to start contributing.As i have little experience with machine learning.
I want to start the topic if i am allowed.

**Comment by mamhoff** [comment]
Hey @iteachmachines sounds great! We already have a [Data Science Co-Learning](https://www.meetup.com/opentechschool-berlin/events) where people do quite a bit of ML. Maybe go there and check it out first? 

These Github issues are for things that need improvement on our website; so I'm closing this PR. Don't take offense :) Have a nice weekend!
