### ISSUE TITLE
Switch Header to One CamelCase Word?

### ISSUE THREAD

**Issue by gnunicorn** [OpenTechSchool/www.opentechschool.org#33]
As we have trouble people writing OpenTechSchool wrong everywhere, the most common mistake seems to be assuming a space between Open and the rest. It might be helpful to use a one line CamelCaseWord in the header of the main page, so that people checkin the spelling get it thrown into their face.

What do you think, @Kriesse , @beatricemartini ?

**Comment by beatricemartini** [comment]
Sounds good! :)

**Comment by gnunicorn** [comment]
@Kriesse doing, postponing or droppping?

**Comment by Kriesse** [comment]
I prefer to not write it in one line, but open for discussion – let's postpone it :)

**Comment by lehmannro** [comment]
Has this been resolved?

**Comment by Ivoz** [comment]
A compounding problem is that the logos in the press and style-guide pages contain pictures in which the text is presented multiline.

If we were to switch, we should make these consistent as well.

**Comment by stefanhoth** [comment]
The new website seems to have taken a decision so I'm closing this issue. @Ivoz is right though about the styleguide. At least the discrepancy should get mentioned.
