### ISSUE TITLE
[PressPage] Multi-Lingual About for copy-paste

### ISSUE THREAD

**Issue by gnunicorn** [OpenTechSchool/www.opentechschool.org#35]
As we had some german press coverage this morning (hint @beatricemartini => put it on the list) of the [german python foundation](http://python-verband.org/news/python-opentechschool) I realised we probably want to have official translations of the about section to copy past in multiple languages, don't we?

//cc @aleksis , @beatricemartini , @Kriesse

**Comment by beatricemartini** [comment]
Or: German (or any other language that might be needed in the future) texts downloadable from the Press area.

So we don't need to have German content showing anywhere in the website (which in this way would be 100% in English)

What do you think?

**Comment by gnunicorn** [comment]
No, this was only about the press-page (as the title says). Of course we do
not want to have all about texts on the website in all languages, but we
should versions of that on the press page. That is all I meant. And I also
added the facilities to switch languages in a tab-like way easily to that
page, so it is just about making it a little prettier and adding the
translation ones we have them.

**Comment by beatricemartini** [comment]
Oops, got it.
Agree 100% :)
