### ISSUE TITLE
More info about interviewees on Testimonials

### ISSUE THREAD

**Issue by Kriesse** [OpenTechSchool/www.opentechschool.org#38]
It would nice to provide some more background about the interviewees in the testimonials, in a list right next to their portrait – maybe which workshop did they attend, in which city, etc… you can think about better examples. 
Also would help to make the layout more engaging and easier to consume.
Thoughts?

I put a placeholder next to Anne's interview.

**Comment by beatricemartini** [comment]
See first line in the testimonial text files stored in Dropbox.
Name, occupation, relationship with OTS.

Cut'n'pasting here:

Annegret Spranger, Community Manager at Photocase.com, Learner
Duana Stanley, Software Developer at Soundcloud, Coach
Frank Cifarelli, Musician and copywriter at Native Instruments, Future Attendee

**Comment by gnunicorn** [comment]
removed ipsum.

**Comment by beatricemartini** [comment]
Checked, edited, closed.
