### ISSUE TITLE
italian translation of about text for press section

### ISSUE THREAD

**Issue by gnunicorn** [OpenTechSchool/www.opentechschool.org#52]

**Comment by beatricemartini** [comment]
OpenTechSchool

OpenTechSchool è un'iniziativa volta ad offrire workshop e meetup
dedicati a tecnologia e linguaggi di programmazione a chiunque voglia
saperne di più, indipendentemente dalla propria esperienza,
professione e sesso. OTS supporta volontari interessati a realizzare
eventi di questo tipo fornendo aiuto dal punto di vista organizzativo
e nella creazione di materiale didattico originale, che viene poi
condiviso online e ulteriormente sviluppato grazie alla collaborazione
della community globale di OTS. Lo scopo principale di OTS è quello di
creare un ambiente confortevole per imparare, dove ci si possa
sentire liberi di porre qualsiasi domanda. Tutti sono invitati a
partecipare, come coach o learner, e a mettersi contatto con OTS per
organizzare eventi ovunque nel mondo.
