### ISSUE TITLE
spanish translation of about text.

### ISSUE THREAD

**Issue by gnunicorn** [OpenTechSchool/www.opentechschool.org#54]
The original is

OpenTechSchool is a community initiative offering free programming workshops and meetups to technology enthusiasts of all genders, backgrounds and experience levels. It supports volunteer coaches in setting up the events taking care of the organizational details and encouraging them to create original teaching material, to be then openly shared online and further developed with contributions from the global OTS community. OTS' main goal is to crate a friendly learning environment where no one feels shy about asking any question. Everyone is invited to participate, whether as a coach or a learner, and get in contact to organize OTS events anywhere in the world.

**Comment by purbon** [comment]
La OpenTechSchool es una iniciativa nacida con el objetivo de ofrecer talleres de programación, y encuentros, gratuitos a entusiastas de la tecnología de todos los niveles, sexos y experiencia. Ofrece soporte durante la organización del evento, fomentando la creación de materiales educativos abiertos y originales, que luego puedan ser mejorados por la comunidad OTS global.  El objetivo principal es crear una comunidad educativa donde nadie tenga vergüenza a preguntar, donde todo el mundo esta invitado a participar ya sea como profesor, alumno o organizando eventos OTS en cualquier parte del mundo.

**Comment by purbon** [comment]
You guys should consider having a Catalan translation also if you want to target event people in Barcelona.

**Comment by gnunicorn** [comment]
If you can provide one by midnight tonight, I'll add it.

**Comment by purbon** [comment]
La OpenTechSchool és una iniciativa nascuda amb l’objectiu d'oferir trobades, i tallers de programació gratuïts, a entusiastes de la tecnologia de tots els nivells, sexes i experiències. Ofereix suport per a l'organització d'esdeveniments, fomentant la creació de materials educatius oberts i originals, que després puguin ser millorats per la comunitat OTS global. L'objectiu principal, és crear una comunitat educativa on ningú tingui vergonya de preguntar, i on tothom esta convidat a participar, ja sigui com a professor, alumne o organitzador. Els esdeveniments OTS es fan a qualsevol part del món.

**Comment by purbon** [comment]
here you've
