### ISSUE TITLE
Indian translation of about text for press section

### ISSUE THREAD

**Issue by gnunicorn** [OpenTechSchool/www.opentechschool.org#56]
The original is

OpenTechSchool is a community initiative offering free programming workshops and meetups to technology enthusiasts of all genders, backgrounds and experience levels. It supports volunteer coaches in setting up the events taking care of the organizational details and encouraging them to create original teaching material, to be then openly shared online and further developed with contributions from the global OTS community. OTS' main goal is to crate a friendly learning environment where no one feels shy about asking any question. Everyone is invited to participate, whether as a coach or a learner, and get in contact to organize OTS events anywhere in the world.

pls make a translation for the next version of our website ...

**Comment by abhinit** [comment]
Ok this one is though! ;) Alryt, here it goes! This is in *Hindi *which is
our national language.

ओपन टेक स्कूल एक सामुदायिक पहल है जिसके द्वारा लोगो के लिए मुफ्त में
प्रोग्रामिंग वोर्क्शोप्स और बैठकों का आयोजन किया जाता है। इन बैठकों में
लोगो के बीच कोई भेदभाव नहीं किया जाता और यह सभी के लिए खुली है। यहाँ हम
उनको प्रोत्साहित करते है जो या तो आगे आके पढाना चाहते है या पढना।हर चीज़ जो
इन वोर्क्शोप्स एवं बैठकों में बनती है वोह पूरी दुनिया के साथ ऑनलाइन बाटी
जाती है ताकि और बाकी ओपन टेक स्कूल से झुदे लोग भी इसमें अपना योगदान दे सके।
ओपन टेक स्कूल का लक्ष्य एक ऐसी जगह का निर्माण करना है जहा लोग कोई भी तकनीकी
प्रष्न पूछ सके।सभी निमंत्रित है, चाहे आप पढना चाहते है या पढाना, या फिर
किसी और जगह ओपन टेक स्कूल की बैठक आयोजित करना चाहते है।हमसे संपर्क करे !

Hope it helps! :)

/Abhinit

On Tue, Dec 4, 2012 at 11:15 PM, Benjamin Kampmann <notifications@github.com
