### ISSUE TITLE
Pictures for headers: Homepage, About, Team

### ISSUE THREAD

**Issue by beatricemartini** [OpenTechSchool/www.opentechschool.org#61]
Dropbox: opentechschool > event pics > WEBSITE: here I picked some pics that might be good for headers

**Comment by beatricemartini** [comment]
Names of the photographers: I added the Stockholm ones directly in the files' names (Lorenzo Pilia and Emma Koszinowski). Don't know the Berlin ones, but as discussed with @ligthyear is not mandatory to mention them.

Thanks!

**Comment by Kriesse** [comment]
I think we should at least credit them in the Impressum? Since the license requires attribution? Links to the city pictures are here: #50

**Comment by gnunicorn** [comment]
already done. They are attributed, which is why I closed that ticket
already...

**Comment by Kriesse** [comment]
ah, sorry, didn't see that :)

**Comment by gnunicorn** [comment]
So, we have Pics in the Header of Berlin and STHLM already. Do we want to have more in About and Team now? Then shouldn't they be more relevant to the page than just a random picture of our events? (Also, as Team is already very visual, do we really need one?) Or did I just misunderstand the point here?

**Comment by beatricemartini** [comment]
I'm ok with both options. The right person to discuss about this with is definitely @Kriesse

**Comment by Kriesse** [comment]
I tried to come up with a solution for now – Pictures on testimonials and about (to show what a workshop looks like and make it less boring). No pictures on homepage (we don't have one that works really well) and team (agreed with Ben, it's a bunch of images already)
