### ISSUE TITLE
Test IE / responsiveness

### ISSUE THREAD

**Issue by Kriesse** [OpenTechSchool/www.opentechschool.org#64]
We should make sure stuff works at least somehow in IE8 and later. We have almost no IE6 and IE7 visits, so we don't care.

**Comment by xMartin** [comment]
IE8 looks very broken :( Fixing #76 helped but CSS layout is not ok.

**Comment by Kriesse** [comment]
Can you take a screenshot?

My guess is we have to import the mediaquery scss into the ie stylesheet, so that IE always get the >768px layout. I can take care of that later.

**Comment by xMartin** [comment]
Sorry, messed up issue numbers.
