### ISSUE TITLE
/about.html -> add non-profit as core value

### ISSUE THREAD

**Issue by janl** [OpenTechSchool/www.opentechschool.org#65]
For example:

Non-Profit
OTS is a non-profit organisation. We believe in coaches and OTS members donating their personal time for the greater good of the community. Courses are run at little or no-cost and are self-organised. There is no need for corporate sponsorship to fund the day-to-day business of OTS. For extracurricular events, like OTS parties for example, sponsors for drinks and music are welcome. Commercial interests can never govern the operation of OTS.

**Comment by janl** [comment]
cc @beatricemartini (via Kriesse)

**Comment by beatricemartini** [comment]
Forwarding to @ligthyear – your take?
