### ISSUE TITLE
Using browser history via swipe looks broken on Safari

### ISSUE THREAD

**Issue by xMartin** [OpenTechSchool/www.opentechschool.org#70]
Using desktop Safari you can move forward and backwards in history doing a swipe with two fingers on a touch pad. This animates the pages. This currently looks very broken for www2.

Video of my screen: http://name.siarp.de/martin/up/ots-safari.mov

**Comment by gnunicorn** [comment]
Looks good here (on Lion, Safari 6.0/7536.25). Maybe it got fixed meanwhile already?

**Comment by xMartin** [comment]
Got fixed somehow on the way.
