### ISSUE TITLE
Generate Sitemap and Submit it to google 

### ISSUE THREAD

**Issue by gnunicorn** [OpenTechSchool/www.opentechschool.org#82]

**Comment by lehmannro** [comment]
sitemap.xml seems to reference www2.opentechschool.org which does not resolve for me currently.  Also, it's out of date again.  Is there some automated process (as part of Jekyll?) we can employ to keep it synced?

**Comment by gnunicorn** [comment]
I'd say we can:

http://vvv.tobiassjosten.net/jekyll/jekyll-sitemap-without-plugins/
