### ISSUE TITLE
Testimonial carousel not nice in IE9

### ISSUE THREAD

**Issue by xMartin** [OpenTechSchool/www.opentechschool.org#88]
Buttons disappear on hover.

No animation. Progressive enhancement is nice, but IE9 should have an animation in my opinion.

**Comment by sjockers** [comment]
I think that's by design in bootstrap. We could...
1. Replace bootstrap-carousel with something else
2. Patch it to fall back to jQuery transitions in IE

**Comment by Ivoz** [comment]
Could someone reexamine this with the 3.0 bootstrap js?

**Comment by xMartin** [comment]
The problem is still there.

**Comment by xMartin** [comment]
I don't think we need to support IE9 any more.
