### ISSUE TITLE
Dropdown not working on mobile Safari (iOS 5-6)

### ISSUE THREAD

**Issue by sjockers** [OpenTechSchool/www.opentechschool.org#92]
Tapping link in the dropdown closes the dropdown. Probably a bug in bootstrap?

**Comment by sjockers** [comment]
Most probably related to this issue: https://github.com/twitter/bootstrap/issues/4550

**Comment by ahamilton9** [comment]
Same situation, running on the most recent files, but I still can't click links in dropdowns on any mobile browser I've tried.

**Comment by ghost** [comment]
This issue is related to iOS 5 Safari handling  touchstart events poorly. Your best bet is probably to wait out the death of iOS 5.

**Comment by xMartin** [comment]
Same problem for iOS 6.

**Comment by friedger** [comment]
![screenshot_2013-09-13-16-54-51](https://f.cloud.github.com/assets/1449049/1139132/1ab542e4-1c85-11e3-865c-d7a8bb22c505.png)
Same problem for chrome on Android
