### ISSUE TITLE
font broken on windows

### ISSUE THREAD

**Issue by gnunicorn** [OpenTechSchool/www.opentechschool.org#96]
Windows uses the "Montserrat" Font which looks very pixely and broken. See attached screenshot.

![image](https://f.cloud.github.com/assets/40496/5916/edca1f60-43a0-11e2-864c-70b8b7795527.png)

**Comment by Ivoz** [comment]
I think that might actually be Chrome's font rendering on windows, which is a known bug. See how it looks in firefox / IE.

https://code.google.com/p/chromium/issues/detail?id=137692

**Comment by Ivoz** [comment]
Apparently this will be fixed in Chrome proper in release 37, around august.

**Comment by Ivoz** [comment]
AND IT'S FIXED

![aliasing](https://cloud.githubusercontent.com/assets/199266/4072544/2142a046-2e88-11e4-8bbe-e68bebed1761.png)

Never been happier to close a bug
